/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import com.jtattoo.plaf.JTattooUtilities;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import javax.swing.UIClientPropertyKey;
import javax.swing.UIManager;

/**
 *
 * @author breix
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    enum operacion{
        multi,minus,plus,divide,sqrt
    }
    operacion operation = null;
    boolean operationReady = false;
    double num1 = 0,num2 = 0, result = 0;
    
    public VentanaCalculadora() {
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        ChangeFonts.changeFont(this.pnBotones, new Font("Sans Serif", Font.BOLD, 14));
        ChangeFonts.changeFont(this.lblshow, new Font("Sans Serif", Font.BOLD, 30));
        ChangeFonts.changeFont(this.lbloperation, new Font("Sans Serif", Font.BOLD, 20));
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnTotal = new javax.swing.JPanel();
        pnLabel = new javax.swing.JPanel();
        lbloperation = new javax.swing.JLabel();
        lblshow = new javax.swing.JLabel();
        pnBotones = new javax.swing.JPanel();
        btndivide = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnsquare = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnmulti = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnminus = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnplusminus = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnpoint = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        PnTotal.setLayout(new java.awt.GridBagLayout());

        pnLabel.setLayout(new java.awt.GridBagLayout());

        lbloperation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        pnLabel.add(lbloperation, gridBagConstraints);
        lbloperation.getAccessibleContext().setAccessibleName("lblOperacion");

        lblshow.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.75;
        pnLabel.add(lblshow, gridBagConstraints);
        lblshow.getAccessibleContext().setAccessibleName("lblMuestra");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        PnTotal.add(pnLabel, gridBagConstraints);

        pnBotones.setLayout(new java.awt.GridBagLayout());

        btndivide.setText("÷");
        btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btndivide, gridBagConstraints);
        btndivide.getAccessibleContext().setAccessibleName("dividebtn");

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn7, gridBagConstraints);
        btn7.getAccessibleContext().setAccessibleName("7btn");

        btndel.setText("⌫");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btndel, gridBagConstraints);
        btndel.getAccessibleContext().setAccessibleName("delbtn");

        btnsquare.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsquare.setText("√");
        btnsquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsquareActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnsquare, gridBagConstraints);
        btnsquare.getAccessibleContext().setAccessibleName("squarebtn");

        btnc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnc.setText("C");
        btnc.setActionCommand("");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnc, gridBagConstraints);
        btnc.getAccessibleContext().setAccessibleName("btnC");

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn8, gridBagConstraints);
        btn8.getAccessibleContext().setAccessibleName("8btn");

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn9, gridBagConstraints);
        btn9.getAccessibleContext().setAccessibleName("9btn");

        btnmulti.setText("X");
        btnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnmulti, gridBagConstraints);
        btnmulti.getAccessibleContext().setAccessibleName("Xbtn");

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn4, gridBagConstraints);
        btn4.getAccessibleContext().setAccessibleName("4btn");

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn5, gridBagConstraints);
        btn5.getAccessibleContext().setAccessibleName("5btn");

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn6, gridBagConstraints);
        btn6.getAccessibleContext().setAccessibleName("6btn");

        btnminus.setText("-");
        btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnminus, gridBagConstraints);
        btnminus.getAccessibleContext().setAccessibleName("minusbtn");

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn1, gridBagConstraints);
        btn1.getAccessibleContext().setAccessibleName("1btn");

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn2, gridBagConstraints);
        btn2.getAccessibleContext().setAccessibleName("2btn");

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn3, gridBagConstraints);
        btn3.getAccessibleContext().setAccessibleName("3btn");

        btnplus.setText("+");
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnplus, gridBagConstraints);
        btnplus.getAccessibleContext().setAccessibleName("plusbtn");

        btnplusminus.setText("±");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnplusminus, gridBagConstraints);
        btnplusminus.getAccessibleContext().setAccessibleName("plusminusbtn");

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btn0, gridBagConstraints);
        btn0.getAccessibleContext().setAccessibleName("0btn");
        btn0.getAccessibleContext().setAccessibleDescription("");

        btnpoint.setText(".");
        btnpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpointActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnpoint, gridBagConstraints);
        btnpoint.getAccessibleContext().setAccessibleName("pointbtn");

        btnequal.setText("=");
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnBotones.add(btnequal, gridBagConstraints);
        btnequal.getAccessibleContext().setAccessibleName("equalbtn");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        PnTotal.add(pnBotones, gridBagConstraints);

        jMenu1.setText("Usos");

        jMenuItem1.setText("Calculadora Estandar");
        jMenu1.add(jMenuItem1);
        jMenuItem1.getAccessibleContext().setAccessibleName("menuItemCalculadora");

        jMenuItem2.setText("Conversor Divisas");
        jMenu1.add(jMenuItem2);
        jMenuItem2.getAccessibleContext().setAccessibleName("menuItemDivisas");

        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        menuBar.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("usosItem");

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        lblshow.setText(lblshow.getText()+0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        lblshow.setText(lblshow.getText()+1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        lblshow.setText(lblshow.getText()+2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        lblshow.setText(lblshow.getText()+3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        lblshow.setText(lblshow.getText()+4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        lblshow.setText(lblshow.getText()+5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        lblshow.setText(lblshow.getText()+6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        lblshow.setText(lblshow.getText()+7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        lblshow.setText(lblshow.getText()+8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
       lblshow.setText(lblshow.getText()+9);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpointActionPerformed
        lblshow.setText(lblshow.getText()+',');
    }//GEN-LAST:event_btnpointActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        lblshow.setText("");
        lbloperation.setText("");
        operation = null;
        operationReady = false;
    }//GEN-LAST:event_btncActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        if(!lblshow.getText().isEmpty())
        lblshow.setText((lblshow.getText().substring(0,lblshow.getText().length()-1)));
    }//GEN-LAST:event_btndelActionPerformed

    private void btndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivideActionPerformed
        if(!operationReady){
        num1 = Integer.parseInt(lblshow.getText());
        lbloperation.setText(lbloperation.getText()+lblshow.getText()+" ÷ ");
        operation = operacion.divide;
        operationReady = true;
        lblshow.setText("");    
        }else{
            num2 = Double.parseDouble(lblshow.getText());
            num1 = getResult(num1, num2);
            lbloperation.setText(lbloperation.getText()+lblshow.getText()+" ÷ ");
            operation = operacion.divide;
            lblshow.setText(""); 
        }
    }//GEN-LAST:event_btndivideActionPerformed

    private void btnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiActionPerformed
        if(!operationReady){
        num1 = Integer.parseInt(lblshow.getText());
        lbloperation.setText(lbloperation.getText()+lblshow.getText()+" * ");
        operation = operacion.multi;
        operationReady = true;   
        lblshow.setText(""); 
        }else{
            num2 = Double.parseDouble(lblshow.getText());
            num1 = getResult(num1, num2);
            lbloperation.setText(lbloperation.getText()+lblshow.getText()+" * ");
            operation = operacion.multi;
            lblshow.setText(""); 
        }
    }//GEN-LAST:event_btnmultiActionPerformed

    private void btnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusActionPerformed
        if(!operationReady){
            num1 = Integer.parseInt(lblshow.getText());
            lbloperation.setText(lbloperation.getText()+lblshow.getText()+" - ");
            operation = operacion.minus;
            operationReady = true;
            lblshow.setText(""); 
        }else{
            num2 = Double.parseDouble(lblshow.getText());
            num1 = getResult(num1, num2);
            lbloperation.setText(lbloperation.getText()+lblshow.getText()+" - ");
            operation = operacion.minus;
            lblshow.setText(""); 
        }
    }//GEN-LAST:event_btnminusActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        if(!operationReady){
        num1 = Integer.parseInt(lblshow.getText());
        lbloperation.setText(lbloperation.getText()+lblshow.getText()+" + ");
        operation = operacion.plus;
        lblshow.setText(""); 
        }else{
        num2 = Double.parseDouble(lblshow.getText());
        num1 = getResult(num1, num2);
        lbloperation.setText(lbloperation.getText()+lblshow.getText()+" + ");
        operation = operacion.plus;
        lblshow.setText(""); 
        }
            
        
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        if(!lblshow.getText().isEmpty())
        num2 = Double.parseDouble(lblshow.getText());
        getResult(num1, num2);
    
        
        
              
    }//GEN-LAST:event_btnequalActionPerformed

    private void btnsquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsquareActionPerformed
        
    }//GEN-LAST:event_btnsquareActionPerformed

    private double getResult(double num1, double num2){
        if(operationReady || num2!=0){
            if(operation==operacion.divide){
                result = num1/num2;
            }
            if(operation==operacion.multi){
                result = num1*num2;
            }
            if(operation==operacion.plus){
                result = num1+num2;
            }
            if(operation==operacion.minus){
                result = num1-num2;
            }
            if(operation==operacion.sqrt){
                
            }
            operationReady = false;
            lblshow.setText(String.valueOf(result));
            operation = null;
            operationReady = false;
        }
        return result;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnTotal;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndivide;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnminus;
    private javax.swing.JButton btnmulti;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnplusminus;
    private javax.swing.JButton btnpoint;
    private javax.swing.JButton btnsquare;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbloperation;
    private javax.swing.JLabel lblshow;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnLabel;
    // End of variables declaration//GEN-END:variables

    
 
 
    
}
